/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub Class for remote web service 
 */

#if !defined(__SENDNOTIFICATION_CLIENTSTUB_H__INCLUDED_)
#define __SENDNOTIFICATION_CLIENTSTUB_H__INCLUDED_

#include <axis/client/Stub.h>
#include "AxisClientException.h"
#include <axis/ISoapFault.h>

class SendNotification :public Stub
{
public:
	SendNotification(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol=APTHTTP);
	SendNotification(xsd__string url);
public:
	virtual ~SendNotification();
public: 
	xsd__string sendNotification(xsd__string url, xsd__string recipient, xsd__string subject, xsd__string message);
	xsd__string_Array sendNotificationToMany(xsd__string url, xsd__string_Array recipients, xsd__string subject, xsd__string message);
	xsd__string sendNotificationToHPOVNNM(xsd__string url, xsd__string recipient,
		xsd__string subject, 
		xsd__string message,
		xsd__string hostname,
		xsd__int port,
		xsd__string uuid);
	xsd__string sendNotificationToNagios(xsd__string url, xsd__string recipient,
		xsd__string subject, 
		xsd__string message,
		xsd__string rwfile,
		xsd__boolean isService,
		xsd__string hostName,
		xsd__string objectName);
	int getFaultDetail(char** ppcDetail);
};

#endif /* !defined(__SENDNOTIFICATION_CLIENTSTUB_H__INCLUDED_)*/
