#!/bin/sh

DIR=/home/drig/workspace/OpenNotification



#. $DIR/tools/setclasspath
cd $DIR; ant clean_jsp war && cd /opt/tomcat/webapps/ && 
for x in `ps ax|grep tomcat|grep -v grep|awk '{print $1}'`;do kill -9 $x;done &&
cd /opt/tomcat/webapps
rm -rf ../logs/* notification* 
cp $DIR/notification.war  . && ../bin/startup.sh && tail -f ../logs/catalina.out

