#!/bin/sh

DIR=/home/drig/workspace/OpenNotification

#. $DIR/tools/setclasspath
cd /opt/tomcat/webapps
../bin/shutdown.sh && rm -rf ../logs/* notification* ; cd $DIR; ant clean_jsp war && cd /opt/tomcat/webapps/ && cp $DIR/notification.war  . && ../bin/startup.sh && tail -f ../logs/catalina.out

